language: node_js
node_js: 12
cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - yarn run build

before_install:
  - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

after_success:
  - scp -rP $PORT /home/travis/build/Jonathan143/sky-music/dist root@$SERVER_IP_ADDRESS:$SERVER_DIR
  - curl https://sc.ftqq.com/$SCKEY.send?text=sky-music%E9%83%A8%E7%BD%B2%E6%88%90%E5%8A%9F
